export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const SIGNOUT_USER_ERROR = 'SIGN_OUT_USER_ERROR';
export const CREATE_CUSTOM_TOKEN_SUCCESS = 'CREATE_CUSTOM_TOKEN_SUCCESS';
export const CREATE_CUSTOM_TOKEN_ERROR = 'CREATE_CUSTOM_TOKEN_ERROR';

export const CREATE_SPOTIFY_AUTHORIZE_URL_SUCCESS = 'CREATE_SPOTIFY_AUTHORIZE_URL_SUCCESS';
export const CREATE_SPOTIFY_ACCESS_TOKEN_SUCCESS = 'CREATE_SPOTIFY_ACCESS_TOKEN_SUCCESS';

export const FETCH_SPOTIFY_ID_SUCCESS = 'FETCH_SPOTIFY_ID_SUCCESS';
export const FETCH_SPOTIFY_ID_ERROR = 'FETCH_SPOTIFY_ID_ERROR';

export const FETCH_SPOTIFY_PLAYLISTS_SUCCESS = 'FETCH_SPOTIFY_PLAYLISTS_SUCCESS';
export const FETCH_SPOTIFY_PLAYLISTS_ERROR = 'FETCH_SPOTIFY_PLAYLISTS_ERROR';