export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CREATE_SPOTIFY_AUTHORIZE_URL_SUCCESS = 'CREATE_SPOTIFY_AUTHORIZE_URL_SUCCESS';
export const CREATE_SPOTIFY_ACCESS_TOKEN = 'CREATE_SPOTIFY_ACCESS_TOKEN';

export const FETCH_SPOTIFY_ID_SUCCESS = 'FETCH_SPOTIFY_ID_SUCCESS';
export const FETCH_SPOTIFY_ID_ERROR = 'FETCH_SPOTIFY_ID_ERROR';

export const FETCH_SPOTIFY_PLAYLISTS_SUCCESS = 'FETCH_SPOTIFY_PLAYLISTS_SUCCESS';
export const FETCH_SPOTIFY_PLAYLISTS_ERROR = 'FETCH_SPOTIFY_PLAYLISTS_TRACKS_ISSUE';

export const FETCH_SPOTIFY_PLAYLIST_TRACKS_COMPLETE = 'FETCH_SPOTIFY_PLAYLIST_TRACKS_COMPLETE';
export const FETCH_SPOTIFY_PLAYLIST_TRACKS_ISSUE = 'FETCH_SPOTIFY_PLAYLIST_TRACKS_ISSUE';

export const FETCH_AUDIO_FEATURES_FOR_PLAYLIST_COMPLETE = 'FETCH_AUDIO_FEATURES_FOR_PLAYLIST_COMPLETE';
export const FETCH_AUDIO_FEATURES_FOR_PLAYLIST_ISSUE = 'FETCH_AUDIO_FEATURES_FOR_PLAYLIST_ISSUE';

export const SORT_SPOTIFY_ANALYZED_TRACKS = 'SORT_SPOTIFY_ANALYZED_TRACKS';

export const HANDLE_PLAYLIST_SELECT = 'HANDLE_PLAYLIST_SELECT';
export const SET_ACTIVE_PLAYLIST_NAME = 'SET_ACTIVE_PLAYLIST_NAME';

export const SET_OPTIMIZE_BTNS = 'SET_OPTIMIZE_BTNS';
export const SET_SELECTED_OPT_ATTR = 'SET_SELECTED_OPT_ATTR';
export const SET_ACTIVE_TRACKS = 'SET_ACTIVE_TRACKS';

export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_ERROR = 'CREATE_PLAYLIST_ERROR';
export const CREATE_PLAYLIST_RESET = 'CREATE_PLAYLIST_RESET';

export const SET_TOP_TRACKS = 'SET_TOP_TRACKS';
