export let unsortedTracks = [{
    acousticness: 0.388,
    artist: "Adele",
    danceability: 0.12,
    energy: 0.953,
    instrumentalness: 0,
    liveness: 0.257,
    loudness: -0.53,
    mode: 1,
    name: "Black History Month",
    speechiness: null,
    tempo: 0,
    track_href: "https://api.spotify.com/v1/tracks/7CJrXIu3mwtSmxzmpe8NlX",
    uri: "spotify:track:7CJrXIu3mwtSmxzmpe8NlX",
    valence: 20
}, {
    acousticness: 0.65,
    artist: "Bee Gees",
    danceability: 0.31,
    energy: 0.10,
    instrumentalness: 0.38,
    liveness: 0.368,
    loudness: -0.13,
    name: "How Deep is Your Love",
    speechiness: null,
    tempo: 88,
    track_href: "https://api.spotify.com/v1/tracks/7CJrXIu3mwtSmxzmpe8NlX",
    uri: "spotify:track:7CJrXIu3mwtSmxzmpe8NlX",
    valence: 15
}, {
    acousticness: 0.941,
    artist: "Jack Johnson",
    danceability: 0.21,
    energy: 0.11,
    instrumentalness: 0.53,
    liveness: 0.642,
    loudness: -0.14,
    name: "Good People",
    speechiness: 0.1,
    tempo: 72,
    track_href: "https://api.spotify.com/v1/tracks/7CJrXIu3mwtSmxzmpe8NlX",
    uri: "spotify:track:7CJrXIu3mwtSmxzmpe8NlX",
    valence: 76
},
{
    acousticness: 0.014,
    artist: "Snoop Dog",
    danceability: 0.89,
    energy: 0.62,
    instrumentalness: 0.14,
    liveness: 0.17,
    loudness: -0.89,
    mode: 1,
    name: "Who Got Da Funk",
    speechiness: 0.72,
    tempo: 1.42,
    track_href: "https://api.spotify.com/v1/tracks/7CJrXIu3mwtSmxzmpe8NlX",
    uri: "spotify:track:7CJrXIu3mwtSmxzmpe8NlX",
    valence: 23
}];